merge pangolin viewers
rbdlabhaifa/simulatorMapping pull request #20
Opened 2023-08-08 09:49 UTC by Jerryaa98

2023-08-20 12:13 UTC, tzukpolinsky requested changes
please pull the changes from my pangolin and re commit **without the generalSettings**

2023-08-21 06:51 UTC, Jerryaa98 commented
היי צוק
אני חוזר מחול היום, כשאגיע אעשה את השינויים,
תודה לעדכון

On Sun, 20 Aug 2023 at 15:14 tzuk polinsky ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> please pull the changes from my pangolin and re commit *without the
> generalSettings*
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/rbdlabhaifa/simulatorMapping/pull/20#pullrequestreview-1585884556>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ATUHRRMA5DTHUJLR4UGJOVLXWH5QVANCNFSM6AAAAAA3IGQBDM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-08-21 07:25 UTC, tzukpolinsky commented
מוזמן גם מחר להיפגש במעבדה

On Mon, Aug 21, 2023, 09:51 Jerryaa98 ***@***.***> wrote:

> היי צוק
> אני חוזר מחול היום, כשאגיע אעשה את השינויים,
> תודה לעדכון
>
> On Sun, 20 Aug 2023 at 15:14 tzuk polinsky ***@***.***> wrote:
>
> > ***@***.**** requested changes on this pull request.
> >
> > please pull the changes from my pangolin and re commit *without the
> > generalSettings*
> >
> > —
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/rbdlabhaifa/simulatorMapping/pull/20#pullrequestreview-1585884556>,
>
> > or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/ATUHRRMA5DTHUJLR4UGJOVLXWH5QVANCNFSM6AAAAAA3IGQBDM>
>
> > .
> > You are receiving this because you authored the thread.Message ID:
> > ***@***.***>
> >
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/rbdlabhaifa/simulatorMapping/pull/20#issuecomment-1685751651>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJBEUMPTLRRHUT3X75XBT3TXWMAPPANCNFSM6AAAAAA3IGQBDM>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2023-08-29 09:34 UTC, tzukpolinsky approved these changes

2023-08-29 09:34 UTC, merged